### ISSUE TITLE
No-Issue

### ISSUE THREAD

**Issue by asfor94** [paylike/plugin-cscart#2]
Hello,
Thanks for your effort in providing this plugin, I would like to know more about how to develop(steps one by one) my one plugin for a domestic payment processor.
appreciate your help

**Comment by ionutcalara** [comment]
Hi @asfor94, I am afraid that due to lack of time, we can't provide step by step code guidance. Here's a tutorial from cs-cart directly which should be enough to get you started: https://docs.cs-cart.com/latest/developer_guide/addons/tutorials/payment_processor_addon.html

I am closing this as this is not an issue related to the plugin.
